### ISSUE TITLE
How to avoid jaxb-runtime dependency version issue?

### ISSUE THREAD

**Issue by akfujimura25** [ehcache/ehcache3#2925]
Hello,

I'm developing an application with Ehcache3 embedded in Spring Framework as shown below.

```
	<cache:annotation-driven />
	<beans:bean id="cacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
		<beans:property name="cacheManager" ref="cacheManagerFactory" />
	</beans:bean>
	<beans:bean id="cacheManagerFactory" class="org.springframework.cache.jcache.JCacheManagerFactoryBean">
		<beans:property name="cacheManagerUri" value="classpath:ehcache.xml"/>
	</beans:bean>
```

After upgrading the Ehcache version from 3.9.0 to 3.9.1, I got a runtime error with ClassNotFoundException when launching the application.

```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:114)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:90)
	at org.ehcache.jsr107.EhcacheCachingProvider$ConfigSupplier.getConfiguration(EhcacheCachingProvider.java:328)
```

After investigating, the cause seemed to be that as a result of changing the jaxb-runtime version range (#2858), jaxb-runtime version 3.0.0-M5 was retrieved when Maven retrieved the dependent library.
This error could be avoided by adding jaxb-runtime to the application dependencies and overwriting the version.

The problem seems to be that the 3.0.0 series is retrieved for the jaxb-runtime version range `[2.2,3)`, but if there is a better workaround, I would appreciate it.

**Comment by chrisdennis** [comment]
`[2.2,3)` means `2.2 <= version < 3`. I don't know why your setup is pulling 3.0, but it's counter to what Ehcache is requesting. It seems that is par for the course with many build systems today (at least OOTB). There's not a lot I can do about it from this side. JAXB 3+ is using the new Jakarta namespaces so is (at least trivially) incompatible with earlier JAXB releases. You'll need to either ensure that Maven honors the Ehcache version range or nail the version to the floor manually.

**Comment by akfujimura25** [comment]
Thank you for your answer.
I'll respond by manually nailing it to the floor.
