### ISSUE TITLE
NoClassDefFoundError: org/terracotta/dynamic_config/api/json/DynamicConfigJsonModule

### ISSUE THREAD

**Issue by martinisraelsen** [ehcache/ehcache3#3324]
When running **tools/bin/config-tool.sh** in Ehcache clustered 3.11.1 or 3.10.9 I consistently get the following error:

`
Exception in thread "main" java.lang.NoClassDefFoundError: org/terracotta/dynamic_config/api/json/DynamicConfigJsonModule
	at org.terracotta.dynamic_config.cli.api.command.OssServiceProvider.createJsonFactory(OssServiceProvider.java:119)
	at org.terracotta.dynamic_config.cli.api.command.OssServiceProvider.createDiagnosticServiceProvider(OssServiceProvider.java:109)
	at org.terracotta.dynamic_config.cli.api.command.OssServiceProvider.createServices(OssServiceProvider.java:54)
	at org.terracotta.dynamic_config.cli.config_tool.ConfigTool.run(ConfigTool.java:66)
	at org.terracotta.dynamic_config.cli.config_tool.ConfigTool.main(ConfigTool.java:119)
Caused by: java.lang.ClassNotFoundException: org.terracotta.dynamic_config.api.json.DynamicConfigJsonModule
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
`
The same command works in Ehcache clustered 3.9.6.

I used the download links from Ehcache.org:

https://github.com/ehcache/ehcache3/releases/download/v3.11.1/ehcache-clustered-3.11.1-kit.zip
https://github.com/ehcache/ehcache3/releases/download/v3.10.9/ehcache-clustered-3.10.9-kit.tgz
